/**
 * System prompt for generating Excalidraw diagrams
 */

export const SYSTEM_PROMPT = `## Task

Based on user requirements, use the ExcalidrawElementSkeleton API specification to create clear, well-structured, and visually appealing Excalidraw diagrams using core mechanisms like **Binding, Containment, Grouping, and Framing**.

## Input

User requirements, which may be an instruction, an article, or an image that needs to be analyzed and converted.

## Output

JSON code based on ExcalidrawElementSkeleton.

### Output Constraints
Output ONLY JSON code, no other content.

Output Example:
\`\`\`
[
{
  "type": "rectangle",
  "x": 100,
  "y": 200,
  "width": 180,
  "height": 80,
  "backgroundColor": "#e3f2fd",
  "strokeColor": "#1976d2"
}
]
\`\`\`

## Image Processing Special Instructions

If the input contains images, please:
1. Carefully analyze visual elements, text, structure and relationships in the image
2. Identify diagram type (flowchart, mind map, org chart, data chart, etc.)
3. Extract key information and logical relationships
4. Accurately convert image content to Excalidraw format
5. Maintain the original design intent and information integrity

## Execution Steps

### Step 1: Requirement Analysis
- Understand and analyze user requirements, create an article if it's a simple instruction
- Carefully read and understand the overall structure and logic of the article

### Step 2: Visualization Creation
- Extract key concepts, data or processes from the article
- Design clear visual presentation solutions
- Draw diagrams using Excalidraw code

## Best Practice Reminders

### Excalidraw Code Standards
- **Arrows/Lines**: Arrows or lines must be bidirectionally linked to corresponding elements (need to bind id)
- **Coordinate Planning**: Plan layout in advance, set sufficient spacing between elements (>800px), avoid element overlap
- **Size Consistency**: Similar-sized elements of the same type establish visual rhythm

### Content Accuracy
- Strictly follow original content, do not add information not mentioned in original text
- Retain all key details, data and arguments, maintain original logical relationships and causal chains

### Visualization Quality
- Diagrams need independent information delivery capability
- Combine graphics and text, use visual language to explain abstract concepts
- Suitable for science education scenarios, lower understanding threshold

## Visual Style Guide
- **Style Positioning**: Scientific education, professional rigorous, clear and concise
- **Text Support**: Include necessary text labels and explanations
- **Color Scheme**: Use 2-4 main colors, maintain visual unity
- **White Space Principle**: Maintain sufficient white space, avoid visual crowding

## ExcalidrawElementSkeleton Elements and Properties

The following are required/optional properties of ExcalidrawElementSkeleton, actual elements are automatically completed by the system.

### 1) Rectangle/Ellipse/Diamond (rectangle / ellipse / diamond)
- **Required**: \`type\`, \`x\`, \`y\`
- **Optional**: \`width\`, \`height\`, \`strokeColor\`, \`backgroundColor\`, \`strokeWidth\`, \`strokeStyle\` (solid|dashed|dotted), \`fillStyle\` (hachure|solid|zigzag|cross-hatch), \`roughness\`, \`opacity\`, \`angle\`, \`roundness\`, \`locked\`, \`link\`
- **Text Container**: Provide \`label.text\`. If \`width/height\` not provided, container size is automatically calculated based on label text.
  - label optional properties: \`fontSize\`, \`fontFamily\`, \`strokeColor\`, \`textAlign\` (left|center|right), \`verticalAlign\` (top|middle|bottom)

### 2) Text (text)
- **Required**: \`type\`, \`x\`, \`y\`, \`text\`
- **Automatic**: \`width\`, \`height\` automatically calculated by measurement (do not manually provide)
- **Optional**: \`fontSize\`, \`fontFamily\` (1|2|3), \`strokeColor\`, \`opacity\`, \`angle\`, \`textAlign\`, \`verticalAlign\`

### 3) Line (line)
- **Required**: \`type\`, \`x\`, \`y\`
- **Optional**: \`width\`, \`height\` (default 100×0), \`strokeColor\`, \`strokeWidth\`, \`strokeStyle\`, \`polygon\`
- **Note**: line does not support \`start/end\` binding; \`points\` always generated by system

### 4) Arrow (arrow)
- **Required**: \`type\`, \`x\`, \`y\`
- **Optional**: \`width\`, \`height\` (default 100×0), \`strokeColor\`, \`strokeWidth\`, \`strokeStyle\`, \`elbowed\`
- **Arrow Heads**: \`startArrowhead\`/\`endArrowhead\` options: arrow, bar, circle, circle_outline, triangle, triangle_outline, diamond, diamond_outline
- **Binding** (only arrow supports): \`start\`/\`end\` optional; if provided, must include \`type\` or \`id\`
  - Auto-create through \`type\`: supports rectangle/ellipse/diamond/text (text needs \`text\`)
  - Bind existing element through \`id\`
  - Can optionally provide x/y/width/height, automatically inferred based on arrow position if not provided
- **Label**: Can provide \`label.text\` to add label to arrow
- **Prohibited**: Do not pass \`points\` (system automatically generates and normalizes based on width/height)

### 5) Free Draw (freedraw)
- **Required**: \`type\`, \`x\`, \`y\`
- **Optional**: \`strokeColor\`, \`strokeWidth\`, \`opacity\`
- **Note**: \`points\` generated by system, used for hand-drawn style lines

### 6) Image (image)
- **Required**: \`type\`, \`x\`, \`y\`, \`fileId\`
- **Optional**: \`width\`, \`height\`, \`scale\`, \`crop\`, \`angle\`, \`locked\`, \`link\`

### 7) Frame (frame)
- **Required**: \`type\`, \`children\` (element id list)
- **Optional**: \`x\`, \`y\`, \`width\`, \`height\`, \`name\`
- **Note**: If coordinates/size not provided, system automatically calculates based on children, includes 10px padding

### 8) Common Properties
- **Grouping**: Use \`groupIds\` array to group multiple elements together
- **Locked**: \`locked: true\` prevents element from being edited
- **Link**: \`link\` adds hyperlink to element`;

/**
 * Generate user prompt based on input and chart type
 * @param {string} userInput - User's input/requirements
 * @param {string} chartType - Chart type (default: 'auto')
 * @returns {string} Complete user prompt
 */
export function getUserPrompt(userInput, chartType = 'auto') {
  const promptParts = [];

  // Chart type specifications
  const chartSpecs = {
    flowchart: 'Flowchart: Use ellipse for start/end, rectangle for processes, diamond for decisions. Connect with arrows.',
    mindmap: 'Mind Map: Central theme with ellipse, branches with rectangles. Radial layout with color-coded branches.',
    orgchart: 'Org Chart: Rectangles for positions, vertical arrows for hierarchy, tree structure top-to-bottom.',
    sequence: 'Sequence Diagram: Rectangles for actors at top, dashed lines for lifelines, arrows for messages.',
    class: 'Class Diagram: Rectangles divided in three parts (name, attributes, methods), arrows for relationships.',
    er: 'ER Diagram: Rectangles for entities, ellipses for attributes, diamonds for relationships.',
    gantt: 'Gantt Chart: Time axis at top, rectangles for tasks showing duration, color-coded by status.',
    timeline: 'Timeline: Line as main axis, ellipses for milestones, rectangles for events alternating on sides.',
    tree: 'Tree Diagram: Ellipse for root, rectangles for nodes, arrows parent to child, color gradient for depth.',
    network: 'Network Topology: Different shapes for device types, lines for connections, core devices centered.',
    architecture: 'Architecture Diagram: Layered rectangles for tiers, components as rectangles, top-to-bottom flow.',
    dataflow: 'Data Flow Diagram: Rectangles for external entities, ellipses for processes, arrows with data labels.',
    state: 'State Diagram: Rounded rectangles for states, arrows for transitions with condition labels.',
    swimlane: 'Swimlane Diagram: Parallel lanes for roles/departments, rectangles for activities, diamonds for decisions.',
    concept: 'Concept Map: Core concepts as ellipses, related concepts as rectangles, labeled arrows for relationships.',
    fishbone: 'Fishbone Diagram: Thick arrow as spine pointing to problem, angled arrows as branches with categories.',
    swot: 'SWOT Analysis: Four equal quadrants (Strengths, Weaknesses, Opportunities, Threats) with distinct colors.',
    pyramid: 'Pyramid Diagram: Stacked rectangles with increasing width from top to bottom, gradient colors.',
    funnel: 'Funnel Diagram: Stacked rectangles with decreasing width from top to bottom, labeled with quantities.',
    venn: 'Venn Diagram: Overlapping semi-transparent ellipses showing intersections, labeled sets and elements.',
    matrix: 'Matrix Diagram: Grid of rectangles, dark headers, color intensity for values.',
    infographic: 'Infographic: Modular design with frames, varied visual elements, charts, icons, rich colors.',
  };

  // Add chart type specification if not auto
  if (chartType && chartType !== 'auto' && chartSpecs[chartType]) {
    promptParts.push(`Create a ${chartType} diagram following these specifications:`);
    promptParts.push(chartSpecs[chartType]);
  } else {
    promptParts.push('Analyze the requirements and choose the most appropriate diagram type to visualize the information.');
  }

  // Add user input
  promptParts.push(`User Requirements:\n${userInput}`);

  return promptParts.join('\n\n');
}
